<?php


namespace app\modules\admin\controllers;
use yii\filters\AccessControl;

class AppAdminController extends \yii\web\Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ]
        ];
//        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}